### ISSUE TITLE
Sonos 6.0 upgrade

### ISSUE THREAD

**Issue by tiberiumihai** [miho/SonoAir#12] opened 2015-09-19 17:20 UTC
I am a beta tester for Sonos software.

Before upgrading to version 6.0, everything was smooth. I mean youtube and some other videos were delayed until the sound was out on my Sonos Play 1.

Now it's a 3-4 seconds delay. I can not even watch youtube or coursera videos.

Thanks for your work. I will appreciate if you will solve this issue.

**Comment by tiberiumihai** [comment] 2015-09-20 08:40
This is what I get:

```
SonoAir v1.0 (BETA 4.0)
Copyright (c) 2015 Michael Hoffer <info@michaelhoffer.de>
--------------------------------------------------------------
-> using node-v0.10.28-darwin-x64
-> using airsonos by Stephen Wan
   see https://github.com/stephen/airsonos/blob/master/LICENSE
-> starting airsonos module... [done]
--------------------------------------------------------------
Setting up SonoAir for Playroom {192.168.0.101:1400}
strange error flushing buffer ... 
Sep 20, 2015 11:17:11 AM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeService
WARNING: Service descriptor retrieval failed: http://192.168.0.101:1400/ssdp/notfound, 404 Not Found
Sep 20, 2015 11:17:11 AM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeServices
WARNING: Skipping invalid service '(RemoteService) Descriptor: /ssdp/notfound' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:RINCON_B8E937EEAA4201400, Descriptor: http://192.168.0.101:1400/xml/group_description.xml, Root: true
```

group_description.xml contains:

```
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:smartspeaker-audio:device:SpeakerGroup:1</deviceType>
<friendlyName>Playroom</friendlyName>
<manufacturer>SONOS</manufacturer>
<UDN>uuid:RINCON_B8E937EEAA4201400</UDN>
<serviceList>
<service>
<serviceType>urn:smartspeaker-audio:service:SpeakerGroup:1</serviceType>
<serviceId>urn:smartspeaker-audio:serviceId:SpeakerGroup</serviceId>
<controlURL>/ssdp/notfound</controlURL>
<eventSubURL>/ssdp/notfound</eventSubURL>
<SCPDURL>/ssdp/notfound</SCPDURL>
</service>
</serviceList>
</device>
</root>
```

**Comment by miho** [comment] 2015-09-20 20:44
Unfortunately, I can't reproduce this behavior. I don't see the error message on 6.0 or 5.4. does it always happen or just sometimes?

**Comment by kpeanuts** [comment] 2015-12-19 10:45
im getting 3-4 second delay on everything is there any fix? on music and video

**Comment by miho** [comment] 2017-02-15 23:03
Unfortunately, the delay won't be fixed in the foreseeable future.

**Closed as completed** 2017-05-09 17:39 UTC
